# Matrices
## Numpy
* Creando una matriz unidimensional y otra bidimensional utilizando numpy

In [2]:
import numpy as np
matriz = np.array([1,2,3])
print(matriz)
print(matriz.shape)#(3,), 3 elementos ordenados

[1 2 3]
(3,)


In [4]:
#matriz en dos dimensiones
matriz2d = np.array([[10,23,24],[32,53,-1]])
print(matriz2d)
print(matriz2d.shape)#(2,3): 2 filas - 3 columnas

[[10 23 24]
 [32 53 -1]]
(2, 3)


In [6]:
import numpy as np
a = np.array([2,3,5])
b = np.array([3,4,65])
print(a,b) #se imprime las dos matrices

[2 3 5] [ 3  4 65]


---
* **Existen modos más eficaces para crear arrays de 1 dimensión**

In [22]:
array = np.linspace(0,10,20) #linspace: (inicio, final, cant-elemt)
print(array)#linstpace(0,Y,X): nos devuelve X números desde 0 hasta Y.
print("Lenght: ",len(array))

array = np.linspace(0,10,30, endpoint=False, retstep=True)
#El endpoint, hace escapar del último número.
#Retstep=True, incluye al final de cuanto en cuanto está aumentando
print(array)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
Lenght:  20
(array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ,
       3.33333333, 3.66666667, 4.        , 4.33333333, 4.66666667,
       5.        , 5.33333333, 5.66666667, 6.        , 6.33333333,
       6.66666667, 7.        , 7.33333333, 7.66666667, 8.        ,
       8.33333333, 8.66666667, 9.        , 9.33333333, 9.66666667]), 0.3333333333333333)


In [30]:
arr = np.arange(10,20,2)# arange(inicio, final, amplitud)
print(arr)
arr = np.arange(10,20) #por defecto la aplitud es = 1
print(arr)
arr = np.arange(10)#por defecto se inicia en 0
print(arr)

[10 12 14 16 18]
[10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6 7 8 9]


---
* **Espacio que ocupan los arrays de numpy**

In [40]:
import sys
lista = range(10000)
print(sys.getsizeof(1)*len(lista))#Calcula el espacio que ocupa en bytes.
lista_np = np.arange(10000)
print(lista_np.itemsize*lista_np.size)#Espacio que ocupa un array en bytes
print("Se concluye que el espacio de un array es menor que de una lista")

280000
80000
Se concluye que el espacio de un array es menor que de una lista


---
* **Evaluemos la rapidez**