# Matrices
## Numpy
* Creando una matriz unidimensional y otra bidimensional utilizando numpy

In [2]:
import numpy as np
matriz = np.array([1,2,3])
print(matriz)
print(matriz.shape)#(3,), 3 elementos ordenados

[1 2 3]
(3,)


In [4]:
#matriz en dos dimensiones
matriz2d = np.array([[10,23,24],[32,53,-1]])
print(matriz2d)
print(matriz2d.shape)#(2,3): 2 filas - 3 columnas

[[10 23 24]
 [32 53 -1]]
(2, 3)


In [6]:
import numpy as np
a = np.array([2,3,5])
b = np.array([3,4,65])
print(a,b) #se imprime las dos matrices

[2 3 5] [ 3  4 65]


---
* **Existen modos más eficaces para crear arrays de 1 dimensión**

In [22]:
array = np.linspace(0,10,20) #linspace: (inicio, final, cant-elemt)
print(array)#linstpace(0,Y,X): nos devuelve X números desde 0 hasta Y.
print("Lenght: ",len(array))

array = np.linspace(0,10,30, endpoint=False, retstep=True)
#El endpoint, hace escapar del último número.
#Retstep=True, incluye al final de cuanto en cuanto está aumentando
print(array)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
Lenght:  20
(array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ,
       3.33333333, 3.66666667, 4.        , 4.33333333, 4.66666667,
       5.        , 5.33333333, 5.66666667, 6.        , 6.33333333,
       6.66666667, 7.        , 7.33333333, 7.66666667, 8.        ,
       8.33333333, 8.66666667, 9.        , 9.33333333, 9.66666667]), 0.3333333333333333)


In [30]:
arr = np.arange(10,20,2)# arange(inicio, final, amplitud)
print(arr)
arr = np.arange(10,20) #por defecto la aplitud es = 1
print(arr)
arr = np.arange(10)#por defecto se inicia en 0
print(arr)

[10 12 14 16 18]
[10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6 7 8 9]


---
* **Espacio que ocupan los arrays de numpy**

In [40]:
import sys
lista = range(10000)
print(sys.getsizeof(1)*len(lista))#Calcula el espacio que ocupa en bytes.
lista_np = np.arange(10000)
print(lista_np.itemsize*lista_np.size)#Espacio que ocupa un array en bytes
print("Se concluye que el espacio de un array es menor que de una lista")

280000
80000
Se concluye que el espacio de un array es menor que de una lista


---
* **Evaluemos la rapidez (listas vs arrays de numpy)**

In [44]:
import time
SIZE = 2000000
lista1 = range(SIZE)
lista2 = range(SIZE)

lista1_np = np.arange(SIZE)
lista2_np = np.arange(SIZE)

start = time.time()
#zip, nos permite crear un emparejamiento entre elementos igualmente numerados
result = [(x+y) for x,y in zip(lista1, lista2)]
# X Y -> (X,Y) ==> 2 3 -> (2,3)
print(result[:10])#imprime los últimos 10 resultados del zip
print("Tiempo transcurrido 1: ",(time.time()-start)*1000) #milisegundos
print("-----------------------------")

start = time.time()
result = lista1_np + lista2_np
print(result[:10])
print("Tiempo transcurrido 2: ",(time.time()-start)*1000) #milisegundos


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
Tiempo transcurrido 1:  178.76219749450684
-----------------------------
[ 0  2  4  6  8 10 12 14 16 18]
Tiempo transcurrido 2:  21.481752395629883


---
* **Y si queremos hacer matrices**

In [46]:
#A nxm
#B nxm

a = np.array([[2,3],[3,2]])
b = np.array([[3,2],[-1,0]])
print(a)
print("---------------")
print(b)
print("----------------")

#Operación concatenar
c = np.concatenate((a,b))
print(c)#Se imprimen las matrices apiladas


[[2 3]
 [3 2]]
---------------
[[ 3  2]
 [-1  0]]
----------------
[[ 2  3]
 [ 3  2]
 [ 3  2]
 [-1  0]]


In [56]:
c = np.vstack((a,b))
print(c)
print(c.shape)#(filas,columnas)
print("--------------")

c = np.hstack((a,b))
print(c)
print(c.shape)#(filas, columnas)
print("---------------")

c = np.concatenate((a,b),axis=0)#axis=0 || axis=1
print(c)
print("------------------")

c = np.dstack((a,b))
print(c)
print(c.shape)

[[ 2  3]
 [ 3  2]
 [ 3  2]
 [-1  0]]
(4, 2)
--------------
[[ 2  3  3  2]
 [ 3  2 -1  0]]
(2, 4)
---------------
[[ 2  3]
 [ 3  2]
 [ 3  2]
 [-1  0]]
------------------
[[[ 2  3]
  [ 3  2]]

 [[ 3 -1]
  [ 2  0]]]
(2, 2, 2)


### Operaciones con vectores
Los vectores se representan mediante arrays de una dimensión.
En esta parte se explorarará las operaciones básicas.

In [4]:
import numpy as np
vector1 = np.array([10,-2,3,1])
vector2 = np.array([3,1,-23,10])

#Operaciones de elemento a elemento

print("suma\n",vector1 + vector2)
print("diferencia\n",vector1 - vector2)
print("producto\n",vector1 * vector2)

#Multiplicando por un número
print("multiplicando por un número\n",10*vector2)

#producto escalar
print("producto escalar\n",vector1 @ vector2)

suma
 [ 13  -1 -20  11]
diferencia
 [ 7 -3 26 -9]
producto
 [ 30  -2 -69  10]
multiplicando por un número
 [  30   10 -230  100]
producto escalar
 -31


---
## Trabajando con matrices
**¿Y si queremos hacer una matriz?**

* **Matrices importantes vacias con np.empty y np.zeros**


In [25]:
%%time 
#%%xyz, magic comand: ejecuta el codigo con nomalidad con información adicional.
print(np.empty((15000,15000)))

#Son números cercanos a ceros

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
CPU times: user 2.85 ms, sys: 2.7 ms, total: 5.55 ms
Wall time: 11.7 ms


In [26]:
%%time
print(np.zeros((15000,15000)))
#Son números iguales a cero

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
CPU times: user 2.16 ms, sys: 0 ns, total: 2.16 ms
Wall time: 1.97 ms


In [29]:
unos = np.ones((3,2))
print(unos)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


---
**Matriz con todos los valores iguales**

In [30]:
full = 8*unos
print(full)

[[8. 8.]
 [8. 8.]
 [8. 8.]]


---
**Creando una matriz identidad**

In [34]:
identidad1 = np.eye(4,10)
print(identidad1)

print("-----------------")

identidad2 = np.identity(4)
print(identidad2)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
-----------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


---
* **Números aleatorios**


In [36]:
aleatorios = np.random.random((3,3))
print(aleatorios)

[[0.44334101 0.63295272 0.98295881]
 [0.31927691 0.82003321 0.12440958]
 [0.60195719 0.6601965  0.62862879]]


**Aleatorios: en computación no existen. Solo secuencias de repetición muy grandes**

Si deseamos replicar los valores de una generación de números aleatorios se utiliza una ___semilla___

In [39]:
np.random.seed(100)#seed(semilla)
aleatorios = np.random.random((3,3))
print(aleatorios)

[[0.54340494 0.27836939 0.42451759]
 [0.84477613 0.00471886 0.12156912]
 [0.67074908 0.82585276 0.13670659]]


---
* **Encontrar la dimensión de la una matriz**


In [47]:
a = np.array([[2,3,4],[5,6,3],[1,2,3]])
print("Dimensión de la matriz = ",a.ndim)

a = np.ones((3,3))
print(a)

a = np.ones((3,3,2))
print("---DIMENSIONES----")
print(a.ndim)

print("------SHAPE------")
print(a.shape)
print("-----SIZE------")
print(a.size)
print("----DATA TYPE------\n",a.dtype)
print("------ITEM SIZE-----\n",a.itemsize)

Dimensión de la matriz =  2
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
---DIMENSIONES----
3
------SHAPE------
(3, 3, 2)
-----SIZE------
18
----DATA TYPE------
 float64
------ITEM SIZE-----
 8


In [55]:
b = np.array([[1,2,3,4,5,6],[5,6,7,8,2,1],[3,2,3,6,4,3]])
print(b)

b = b.reshape(1,18)
print("\n---RESHAPE----\n",b)

[[1 2 3 4 5 6]
 [5 6 7 8 2 1]
 [3 2 3 6 4 3]]

---RESHAPE----
 [[1 2 3 4 5 6 5 6 7 8 2 1 3 2 3 6 4 3]]


---
**Extraer los valores de una matriz**

In [63]:
b = np.array([[1,2,3,4,5,6],[5,6,7,8,2,1],[3,2,3,6,4,3]])
print(b[0,0]) #valor [0,0]

1


In [65]:
b = np.array([[1,2,3,4,5,6],[5,6,7,8,2,1],[3,2,3,6,4,3]])
print(b,"\n----------")
print(b[0])
print("------")
print(b[:,3])#columna 3

[[1 2 3 4 5 6]
 [5 6 7 8 2 1]
 [3 2 3 6 4 3]] 
----------
[1 2 3 4 5 6]
------
[4 8 6]


## Operaciones con matrices

In [81]:
x = np.random.random((3,3))
y = np.random.random((3,3))
print(x,"\n\t\t----\n",y)

#Operaciones de elemento a elemento
print("\n\t-----Suma------\n",x+y)
print("\n\t-----Diferencia------\n",x-y)
print("\n\t-----Producto------\n",x*y)
print("\n\t-----División------\n",x/y)

[[0.8937521  0.55402119 0.49286651]
 [0.31927046 0.26336578 0.54228061]
 [0.08226452 0.63563671 0.79640523]] 
		----
 [[0.95474751 0.68462427 0.48829317]
 [0.48541431 0.96669292 0.21134789]
 [0.41164814 0.98966558 0.02841186]]

	-----SUMA------
 [[1.84849961 1.23864546 0.98115967]
 [0.80468477 1.2300587  0.7536285 ]
 [0.49391266 1.62530229 0.82481708]]

	-----Diferencia------
 [[-0.0609954  -0.13060308  0.00457334]
 [-0.16614385 -0.70332714  0.33093273]
 [-0.32938361 -0.35402887  0.76799337]]

	-----Producto------
 [[0.85330759 0.37929635 0.24066335]
 [0.15497845 0.25459384 0.11460986]
 [0.03386404 0.62906777 0.02262735]]

	-----División------
 [[ 0.93611358  0.80923393  1.00936597]
 [ 0.65772774  0.27243996  2.56581989]
 [ 0.19984185  0.64227424 28.03073496]]


---
**Producto de matrices**: 
* Es una operación bastante utilizada.
* Es una operación no conmutativa.
* Se requiere que el número de columnas de la 1ra sea igual al número de filas del 2da.

In [87]:
A = np.random.random((3,2))
B = np.random.random((2,4))

print("\t\t----Producto 1-----\n",np.matmul(A,B))
print("\n\t\t----Producto 2-----\n",A.dot(B))#otra forma de multiplicar matrices

		----Producto 1-----
 [[0.08944842 0.29118601 0.4097896  0.37134401]
 [0.15998917 0.22434363 0.39582136 0.2824503 ]
 [0.0455952  0.4603686  0.5636048  0.59094065]]

		----Producto 2-----
 [[0.08944842 0.29118601 0.4097896  0.37134401]
 [0.15998917 0.22434363 0.39582136 0.2824503 ]
 [0.0455952  0.4603686  0.5636048  0.59094065]]


In [88]:
%%time
print("\t\t----Producto 1-----\n",np.matmul(A,B))

		----Producto 1-----
 [[0.08944842 0.29118601 0.4097896  0.37134401]
 [0.15998917 0.22434363 0.39582136 0.2824503 ]
 [0.0455952  0.4603686  0.5636048  0.59094065]]
CPU times: user 292 µs, sys: 63 µs, total: 355 µs
Wall time: 354 µs


In [89]:
%%time
print("\n\t\t----Producto 2-----\n",A.dot(B))#otra forma de multiplicar matrices


		----Producto 2-----
 [[0.08944842 0.29118601 0.4097896  0.37134401]
 [0.15998917 0.22434363 0.39582136 0.2824503 ]
 [0.0455952  0.4603686  0.5636048  0.59094065]]
CPU times: user 2.65 ms, sys: 0 ns, total: 2.65 ms
Wall time: 8.48 ms


In [90]:
#Transpuesta
C = np.random.random((4,2))
print(C)
print(C.shape)
C = C.T
print(C.shape)

[[0.32136584 0.09271987]
 [0.06043793 0.09095117]
 [0.68270646 0.68073577]
 [0.24317417 0.64046144]]
(4, 2)
(2, 4)


In [97]:
#Inversa de una matriz
#A*? = 1
A = np.array([[4,2],[3,10]])
print(A)
invA = np.linalg.inv(A)
print("\t-----Inversa de A------\n",invA)

#Comprobar si es la inversa de A
r = np.matmul(A,invA)
print("\n\t---------\n",r)

[[ 4  2]
 [ 3 10]]
	-----Inversa de A------
 [[ 0.29411765 -0.05882353]
 [-0.08823529  0.11764706]]

	---------
 [[ 1.00000000e+00  0.00000000e+00]
 [-1.11022302e-16  1.00000000e+00]]


In [98]:
#Determinante de una matriz, se hace solo para una matriz cuadrada
B = np.array([[2,5,21],[4,3,1],[-1,3,4]])
det = np.linalg.det(B)
print(det)

248.00000000000009


In [101]:
#Autovalores y autovectores (eigenvalores eigenvectores)
C = np.array([[2,5,21],[4,3,1],[-1,3,4]])
print(C)

np.linalg.eig(C)#autovalores y autovectores

[[ 2  5 21]
 [ 4  3  1]
 [-1  3  4]]


(array([-0.14505104+5.16469149j, -0.14505104-5.16469149j,
         9.29010209+0.j        ]),
 array([[ 0.7942039 +0.j        ,  0.7942039 -0.j        ,
          0.82227366+0.j        ],
        [-0.22748402-0.47135544j, -0.22748402+0.47135544j,
          0.54755469+0.j        ],
        [-0.02696132+0.30755216j, -0.02696132-0.30755216j,
          0.15508026+0.j        ]]))