# Matrices
## Numpy
* Creando una matriz unidimensional y otra bidimensional utilizando numpy

In [2]:
import numpy as np
matriz = np.array([1,2,3])
print(matriz)
print(matriz.shape)#(3,), 3 elementos ordenados

[1 2 3]
(3,)


In [4]:
#matriz en dos dimensiones
matriz2d = np.array([[10,23,24],[32,53,-1]])
print(matriz2d)
print(matriz2d.shape)#(2,3): 2 filas - 3 columnas

[[10 23 24]
 [32 53 -1]]
(2, 3)


In [6]:
import numpy as np
a = np.array([2,3,5])
b = np.array([3,4,65])
print(a,b) #se imprime las dos matrices

[2 3 5] [ 3  4 65]


---
* **Existen modos más eficaces para crear arrays de 1 dimensión**

In [22]:
array = np.linspace(0,10,20) #linspace: (inicio, final, cant-elemt)
print(array)#linstpace(0,Y,X): nos devuelve X números desde 0 hasta Y.
print("Lenght: ",len(array))

array = np.linspace(0,10,30, endpoint=False, retstep=True)
#El endpoint, hace escapar del último número.
#Retstep=True, incluye al final de cuanto en cuanto está aumentando
print(array)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
Lenght:  20
(array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ,
       3.33333333, 3.66666667, 4.        , 4.33333333, 4.66666667,
       5.        , 5.33333333, 5.66666667, 6.        , 6.33333333,
       6.66666667, 7.        , 7.33333333, 7.66666667, 8.        ,
       8.33333333, 8.66666667, 9.        , 9.33333333, 9.66666667]), 0.3333333333333333)


In [30]:
arr = np.arange(10,20,2)# arange(inicio, final, amplitud)
print(arr)
arr = np.arange(10,20) #por defecto la aplitud es = 1
print(arr)
arr = np.arange(10)#por defecto se inicia en 0
print(arr)

[10 12 14 16 18]
[10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6 7 8 9]


---
* **Espacio que ocupan los arrays de numpy**

In [40]:
import sys
lista = range(10000)
print(sys.getsizeof(1)*len(lista))#Calcula el espacio que ocupa en bytes.
lista_np = np.arange(10000)
print(lista_np.itemsize*lista_np.size)#Espacio que ocupa un array en bytes
print("Se concluye que el espacio de un array es menor que de una lista")

280000
80000
Se concluye que el espacio de un array es menor que de una lista


---
* **Evaluemos la rapidez (listas vs arrays de numpy)**

In [44]:
import time
SIZE = 2000000
lista1 = range(SIZE)
lista2 = range(SIZE)

lista1_np = np.arange(SIZE)
lista2_np = np.arange(SIZE)

start = time.time()
#zip, nos permite crear un emparejamiento entre elementos igualmente numerados
result = [(x+y) for x,y in zip(lista1, lista2)]
# X Y -> (X,Y) ==> 2 3 -> (2,3)
print(result[:10])#imprime los últimos 10 resultados del zip
print("Tiempo transcurrido 1: ",(time.time()-start)*1000) #milisegundos
print("-----------------------------")

start = time.time()
result = lista1_np + lista2_np
print(result[:10])
print("Tiempo transcurrido 2: ",(time.time()-start)*1000) #milisegundos


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
Tiempo transcurrido 1:  178.76219749450684
-----------------------------
[ 0  2  4  6  8 10 12 14 16 18]
Tiempo transcurrido 2:  21.481752395629883


---
* **Y si queremos hacer matrices**

In [46]:
#A nxm
#B nxm

a = np.array([[2,3],[3,2]])
b = np.array([[3,2],[-1,0]])
print(a)
print("---------------")
print(b)
print("----------------")

#Operación concatenar
c = np.concatenate((a,b))
print(c)#Se imprimen las matrices apiladas


[[2 3]
 [3 2]]
---------------
[[ 3  2]
 [-1  0]]
----------------
[[ 2  3]
 [ 3  2]
 [ 3  2]
 [-1  0]]


In [56]:
c = np.vstack((a,b))
print(c)
print(c.shape)#(filas,columnas)
print("--------------")

c = np.hstack((a,b))
print(c)
print(c.shape)#(filas, columnas)
print("---------------")

c = np.concatenate((a,b),axis=0)#axis=0 || axis=1
print(c)
print("------------------")

c = np.dstack((a,b))
print(c)
print(c.shape)

[[ 2  3]
 [ 3  2]
 [ 3  2]
 [-1  0]]
(4, 2)
--------------
[[ 2  3  3  2]
 [ 3  2 -1  0]]
(2, 4)
---------------
[[ 2  3]
 [ 3  2]
 [ 3  2]
 [-1  0]]
------------------
[[[ 2  3]
  [ 3  2]]

 [[ 3 -1]
  [ 2  0]]]
(2, 2, 2)


### Operaciones con vectores
Los vectores se representan mediante arrays de una dimensión.
En esta parte se explorarará las operaciones básicas.

In [4]:
import numpy as np
vector1 = np.array([10,-2,3,1])
vector2 = np.array([3,1,-23,10])

#Operaciones de elemento a elemento

print("suma\n",vector1 + vector2)
print("diferencia\n",vector1 - vector2)
print("producto\n",vector1 * vector2)

#Multiplicando por un número
print("multiplicando por un número\n",10*vector2)

#producto escalar
print("producto escalar\n",vector1 @ vector2)

suma
 [ 13  -1 -20  11]
diferencia
 [ 7 -3 26 -9]
producto
 [ 30  -2 -69  10]
multiplicando por un número
 [  30   10 -230  100]
producto escalar
 -31


---
## Trabajando con matrices
**¿Y si queremos hacer una matriz?**

* **Matrices importantes vacias con np.empty y np.zeros**


In [25]:
%%time 
#%%xyz, magic comand: ejecuta el codigo con nomalidad con información adicional.
print(np.empty((15000,15000)))

#Son números cercanos a ceros

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
CPU times: user 2.85 ms, sys: 2.7 ms, total: 5.55 ms
Wall time: 11.7 ms


In [26]:
%%time
print(np.zeros((15000,15000)))
#Son números iguales a cero

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
CPU times: user 2.16 ms, sys: 0 ns, total: 2.16 ms
Wall time: 1.97 ms


In [29]:
unos = np.ones((3,2))
print(unos)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


---
**Matriz con todos los valores iguales**

In [30]:
full = 8*unos
print(full)

[[8. 8.]
 [8. 8.]
 [8. 8.]]


---
**Creando una matriz identidad**

In [34]:
identidad1 = np.eye(4,10)
print(identidad1)

print("-----------------")

identidad2 = np.identity(4)
print(identidad2)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
-----------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


---
* **Números aleatorios**


In [36]:
aleatorios = np.random.random((3,3))
print(aleatorios)

[[0.44334101 0.63295272 0.98295881]
 [0.31927691 0.82003321 0.12440958]
 [0.60195719 0.6601965  0.62862879]]


**Aleatorios: en computación no existen. Solo secuencias de repetición muy grandes**

Si deseamos replicar los valores de una generación de números aleatorios se utiliza una ___semilla___

In [39]:
np.random.seed(100)#seed(semilla)
aleatorios = np.random.random((3,3))
print(aleatorios)

[[0.54340494 0.27836939 0.42451759]
 [0.84477613 0.00471886 0.12156912]
 [0.67074908 0.82585276 0.13670659]]


---
* **Encontrar la dimensión de la una matriz**


In [47]:
a = np.array([[2,3,4],[5,6,3],[1,2,3]])
print("Dimensión de la matriz = ",a.ndim)

a = np.ones((3,3))
print(a)

a = np.ones((3,3,2))
print("---DIMENSIONES----")
print(a.ndim)

print("------SHAPE------")
print(a.shape)
print("-----SIZE------")
print(a.size)
print("----DATA TYPE------\n",a.dtype)
print("------ITEM SIZE-----\n",a.itemsize)

Dimensión de la matriz =  2
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
---DIMENSIONES----
3
------SHAPE------
(3, 3, 2)
-----SIZE------
18
----DATA TYPE------
 float64
------ITEM SIZE-----
 8


In [55]:
b = np.array([[1,2,3,4,5,6],[5,6,7,8,2,1],[3,2,3,6,4,3]])
print(b)

b = b.reshape(1,18)
print("\n---RESHAPE----\n",b)

[[1 2 3 4 5 6]
 [5 6 7 8 2 1]
 [3 2 3 6 4 3]]

---RESHAPE----
 [[1 2 3 4 5 6 5 6 7 8 2 1 3 2 3 6 4 3]]


---
**Extraer los valores de una matriz**

In [63]:
b = np.array([[1,2,3,4,5,6],[5,6,7,8,2,1],[3,2,3,6,4,3]])
print(b[0,0]) #valor [0,0]

1


In [65]:
b = np.array([[1,2,3,4,5,6],[5,6,7,8,2,1],[3,2,3,6,4,3]])
print(b,"\n----------")
print(b[0])
print("------")
print(b[:,3])#columna 3

[[1 2 3 4 5 6]
 [5 6 7 8 2 1]
 [3 2 3 6 4 3]] 
----------
[1 2 3 4 5 6]
------
[4 8 6]
